In [2]:

from pathlib import Path
from _dataclasses import Dataset
import lightning.pytorch as pl

In [3]:
dataset= Dataset.load()

In [4]:
dataset.encoding

   category name
0            ekl
1            zdr
2            fin
3            kul
4            mag
5            bur
6            che
7            ene
8            sur
9            buk
10           pit
11           tlk
12           zak
13           obo
14           efm
15           odb
16           pol
17           eur
18           dpr
19           bup
20           sop
21           slz
22           spo
23           for
24           mak
25           hok
26           sta
27           pod
28           str
29           aut
30           met
31           kat
32           slo
33           bos
34           ptr
35           sko
36           den
37           zem
38           spl
39           prm
40           vat
41           tok
42           tur
43           med
44           eko
45           mix
46           prg
47           bsk
48           bua
49           dre
50           fot
51           pla
52           hut
53           nab
54           zah
55           mot
56           zbr
57           reg
58           cen
59           spc

In [4]:
frac = dataset.split()

In [9]:
frac.save(texts_path = Path("./data/test_dataset.csv"))

In [10]:
dataset.save(texts_path = Path("./data/train_dataset.csv"))